version: '3.4'

services:
  sodimacgw.api:
    image: ${DOCKER_REGISTRY-}sodimacgwapi
    build:
      context: .
      dockerfile: src\ApiGateways\SodimacGW.API\Dockerfile

  asnverify.api:
    image: ${DOCKER_REGISTRY-}asnverifyapi
    build:
      context: .
      dockerfile: src\Services\ASNVerify.API\Dockerfile


  ordencompra.api:
    image: ${DOCKER_REGISTRY-}ordencompraapi
    build:
      context: .
      dockerfile: src\Services\OrdenCompra\Dockerfile


  shipconfirm.api:
    image: ${DOCKER_REGISTRY-}shipconfirmapi
    build:
      context: .
      dockerfile: src\Services\ShipConfirm.API\Dockerfile


  distributionorder.api:
    image: ${DOCKER_REGISTRY-}distributionorderapi
    build:
      context: .
      dockerfile: src\Services\DistributionOrder.API\Dockerfile

