version: '3.4'

services:
  sodimacgw.api:
    image: ${DOCKER_REGISTRY-}sodimacgwapi
    build:
      context: .
      dockerfile: src\ApiGateways\SodimacGW.API\Dockerfile

  asnverify.api:
    image: ${DOCKER_REGISTRY-}asnverifyapi
    build:
      context: .
      dockerfile: src\Services\ASNVerify.API\Dockerfile


  dispatchorder.api:
    image: ${DOCKER_REGISTRY-}dispatchorderapi
    build:
      context: .
      dockerfile: src\Services\DispatchOrder.API\Dockerfile


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src\Services\Identity.API\Dockerfile


  ordencompra.api:
    image: ${DOCKER_REGISTRY-}ordencompraapi
    build:
      context: .
      dockerfile: src\Services\OrdenCompra\Dockerfile


  shipconfirm.api:
    image: ${DOCKER_REGISTRY-}shipconfirmapi
    build:
      context: .
      dockerfile: src\Services\ShipConfirm.API\Dockerfile

